version: '3.5'
services:
    db:
      container_name: db_pomodorc
      image: mongo
      command: mongod --quiet --logpath /dev/null
      ports: 
          - 27017:27017

    api:
        depends_on:
            - db
        volumes: 
            - ./server:/app
            - ./server/node_modules:/app/node_modules
        container_name: backend_pomodorc
        environment:
            - DATABASE_URL=mongodb://db/pomodorc
        build:
            context: ./server
        ports:
            - "5000:5000"
        command: npm start
    
    
    front: 
        build: front
        environment:
            CHOKIDAR_USEPOLLING: "true"
        volumes: 
            - ./front:/app
            - ./front/node_modules:/app/node_modules
        container_name: frontend_pomodorc
        build:
            context: ./front
        command: yarn start
        ports:
            - "3000:3000"
        depends_on:
            - api